module.exports =  {
  "hiragana":[
    [
      {
        "sound":"a",
        "kana":"\u3042"
      },
      {
        "sound":"i",
        "kana":"\u3044"
      },
      {
        "sound":"u",
        "kana":"\u3046"
      },
      {
        "sound":"e",
        "kana":"\u3048"
      },
      {
        "sound":"o",
        "kana":"\u304a"
      }
    ],
    [
      {
        "sound":"ka",
        "kana":"\u304b"
      },
      {
        "sound":"ki",
        "kana":"\u304d"
      },
      {
        "sound":"ku",
        "kana":"\u304f"
      },
      {
        "sound":"ke",
        "kana":"\u3051"
      },
      {
        "sound":"ko",
        "kana":"\u3053"
      }
    ],
    [
      {
        "sound":"sa",
        "kana":"\u3055"
      },
      {
        "sound":"shi",
        "kana":"\u3057"
      },
      {
        "sound":"su",
        "kana":"\u3059"
      },
      {
        "sound":"se",
        "kana":"\u305b"
      },
      {
        "sound":"so",
        "kana":"\u305d"
      }
    ],
    [
      {
        "sound":"ta",
        "kana":"\u305f"
      },
      {
        "sound":"chi",
        "kana":"\u3061"
      },
      {
        "sound":"tsu",
        "kana":"\u3064"
      },
      {
        "sound":"te",
        "kana":"\u3066"
      },
      {
        "sound":"to",
        "kana":"\u3068"
      }
    ],
    [
      {
        "sound":"na",
        "kana":"\u306a"
      },
      {
        "sound":"ni",
        "kana":"\u306b"
      },
      {
        "sound":"nu",
        "kana":"\u306c"
      },
      {
        "sound":"ne",
        "kana":"\u306d"
      },
      {
        "sound":"no",
        "kana":"\u306e"
      }
    ],
    [
      {
        "sound":"ha",
        "kana":"\u306f"
      },
      {
        "sound":"hi",
        "kana":"\u3072"
      },
      {
        "sound":"fu",
        "kana":"\u3075"
      },
      {
        "sound":"he",
        "kana":"\u3078"
      },
      {
        "sound":"ho",
        "kana":"\u307b"
      }
    ],
    [
      {
        "sound":"ma",
        "kana":"\u307e"
      },
      {
        "sound":"mi",
        "kana":"\u307f"
      },
      {
        "sound":"mu",
        "kana":"\u3080"
      },
      {
        "sound":"me",
        "kana":"\u3081"
      },
      {
        "sound":"mo",
        "kana":"\u3082"
      }
    ],
    [
      {
        "sound":"ya",
        "kana":"\u3084"
      },
      {
        "sound":"yu",
        "kana":"\u3086"
      },
      {
        "sound":"yo",
        "kana":"\u3088"
      }
    ],
    [
      {
        "sound":"ra",
        "kana":"\u3089"
      },
      {
        "sound":"ri",
        "kana":"\u308a"
      },
      {
        "sound":"ru",
        "kana":"\u308b"
      },
      {
        "sound":"re",
        "kana":"\u308c"
      },
      {
        "sound":"ro",
        "kana":"\u308d"
      }
    ],
    [
      {
        "sound":"wa",
        "kana":"\u308f"
      },
      {
        "sound":"o/wo",
        "kana":"\u3092"
      }
    ],
    [
      {
        "sound":"n",
        "kana":"\u3093"
      }
    ],
    [
      {
        "sound":"ga",
        "kana":"\u304c"
      },
      {
        "sound":"gi",
        "kana":"\u304e"
      },
      {
        "sound":"gu",
        "kana":"\u3050"
      },
      {
        "sound":"ge",
        "kana":"\u3052"
      },
      {
        "sound":"go",
        "kana":"\u3054"
      }
    ],
    [
      {
        "sound":"za",
        "kana":"\u3056"
      },
      {
        "sound":"ji",
        "kana":"\u3058"
      },
      {
        "sound":"zu",
        "kana":"\u305a"
      },
      {
        "sound":"ze",
        "kana":"\u305c"
      },
      {
        "sound":"zo",
        "kana":"\u305e"
      }
    ],
    [
      {
        "sound":"da",
        "kana":"\u3060"
      },
      {
        "sound":"de",
        "kana":"\u3067"
      },
      {
        "sound":"do",
        "kana":"\u3069"
      }
    ],
    [
      {
        "sound":"ba",
        "kana":"\u3070"
      },
      {
        "sound":"bi",
        "kana":"\u3073"
      },
      {
        "sound":"bu",
        "kana":"\u3076"
      },
      {
        "sound":"be",
        "kana":"\u3079"
      },
      {
        "sound":"bo",
        "kana":"\u307c"
      }
    ],
    [
      {
        "sound":"pa",
        "kana":"\u3071"
      },
      {
        "sound":"pi",
        "kana":"\u3074"
      },
      {
        "sound":"pu",
        "kana":"\u3077"
      },
      {
        "sound":"pe",
        "kana":"\u307a"
      },
      {
        "sound":"po",
        "kana":"\u307d"
      }
    ],
    [
      {
        "sound":"kya",
        "kana":"\u304d\u3083"
      },
      {
        "sound":"kyu",
        "kana":"\u304d\u3085"
      },
      {
        "sound":"kyo",
        "kana":"\u304d\u3087"
      }
    ],
    [
      {
        "sound":"sha",
        "kana":"\u3057\u3083"
      },
      {
        "sound":"shu",
        "kana":"\u3057\u3085"
      },
      {
        "sound":"sho",
        "kana":"\u3057\u3087"
      }
    ],
    [
      {
        "sound":"cha",
        "kana":"\u3061\u3083"
      },
      {
        "sound":"chu",
        "kana":"\u3061\u3085"
      },
      {
        "sound":"cho",
        "kana":"\u3061\u3087"
      }
    ],
    [
      {
        "sound":"nya",
        "kana":"\u306b\u3083"
      },
      {
        "sound":"nyu",
        "kana":"\u306b\u3085"
      },
      {
        "sound":"nyo",
        "kana":"\u306b\u3087"
      }
    ],
    [
      {
        "sound":"hya",
        "kana":"\u3072\u3083"
      },
      {
        "sound":"hyu",
        "kana":"\u3072\u3085"
      },
      {
        "sound":"hyo",
        "kana":"\u3072\u3087"
      }
    ],
    [
      {
        "sound":"mya",
        "kana":"\u307f\u3083"
      },
      {
        "sound":"myu",
        "kana":"\u307f\u3085"
      },
      {
        "sound":"myo",
        "kana":"\u307f\u3087"
      }
    ],
    [
      {
        "sound":"rya",
        "kana":"\u308a\u3083"
      },
      {
        "sound":"ryu",
        "kana":"\u308a\u3085"
      },
      {
        "sound":"ryo",
        "kana":"\u308a\u3087"
      }
    ],
    [
      {
        "sound":"gya",
        "kana":"\u304e\u3083"
      },
      {
        "sound":"gyu",
        "kana":"\u304e\u3085"
      },
      {
        "sound":"gyo",
        "kana":"\u304e\u3087"
      }
    ],
    [
      {
        "sound":"ja",
        "kana":"\u3058\u3083"
      },
      {
        "sound":"ju",
        "kana":"\u3058\u3085"
      },
      {
        "sound":"jo",
        "kana":"\u3058\u3087"
      }
    ],
    [
      {
        "sound":"bya",
        "kana":"\u3073\u3083"
      },
      {
        "sound":"byu",
        "kana":"\u3073\u3085"
      },
      {
        "sound":"byo",
        "kana":"\u3073\u3087"
      }
    ],
    [
      {
        "sound":"pya",
        "kana":"\u3074\u3083"
      },
      {
        "sound":"pyu",
        "kana":"\u3074\u3085"
      },
      {
        "sound":"pyo",
        "kana":"\u3074\u3087"
      }
    ]
  ],
  "katakana":[
    [
      {
        "sound":"a",
        "kana":"\u30a2"
      },
      {
        "sound":"i",
        "kana":"\u30a4"
      },
      {
        "sound":"u",
        "kana":"\u30a6"
      },
      {
        "sound":"e",
        "kana":"\u30a8"
      },
      {
        "sound":"o",
        "kana":"\u30aa"
      }
    ],
    [
      {
        "sound":"ka",
        "kana":"\u30ab"
      },
      {
        "sound":"ki",
        "kana":"\u30ad"
      },
      {
        "sound":"ku",
        "kana":"\u30af"
      },
      {
        "sound":"ke",
        "kana":"\u30b1"
      },
      {
        "sound":"ko",
        "kana":"\u30b3"
      }
    ],
    [
      {
        "sound":"sa",
        "kana":"\u30b5"
      },
      {
        "sound":"shi",
        "kana":"\u30b7"
      },
      {
        "sound":"su",
        "kana":"\u30b9"
      },
      {
        "sound":"se",
        "kana":"\u30bb"
      },
      {
        "sound":"so",
        "kana":"\u30bd"
      }
    ],
    [
      {
        "sound":"ta",
        "kana":"\u30bf"
      },
      {
        "sound":"chi",
        "kana":"\u30c1"
      },
      {
        "sound":"tsu",
        "kana":"\u30c4"
      },
      {
        "sound":"te",
        "kana":"\u30c6"
      },
      {
        "sound":"to",
        "kana":"\u30c8"
      }
    ],
    [
      {
        "sound":"na",
        "kana":"\u30ca"
      },
      {
        "sound":"ni",
        "kana":"\u30cb"
      },
      {
        "sound":"nu",
        "kana":"\u30cc"
      },
      {
        "sound":"ne",
        "kana":"\u30cd"
      },
      {
        "sound":"no",
        "kana":"\u30ce"
      }
    ],
    [
      {
        "sound":"ha",
        "kana":"\u30cf"
      },
      {
        "sound":"hi",
        "kana":"\u30d2"
      },
      {
        "sound":"fu",
        "kana":"\u30d5"
      },
      {
        "sound":"he",
        "kana":"\u30d8"
      },
      {
        "sound":"ho",
        "kana":"\u30db"
      }
    ],
    [
      {
        "sound":"ma",
        "kana":"\u30de"
      },
      {
        "sound":"mi",
        "kana":"\u30df"
      },
      {
        "sound":"mu",
        "kana":"\u30e0"
      },
      {
        "sound":"me",
        "kana":"\u30e1"
      },
      {
        "sound":"mo",
        "kana":"\u30e2"
      }
    ],
    [
      {
        "sound":"ya",
        "kana":"\u30e4"
      },
      {
        "sound":"yu",
        "kana":"\u30e6"
      },
      {
        "sound":"yo",
        "kana":"\u30e8"
      }
    ],
    [
      {
        "sound":"ra",
        "kana":"\u30e9"
      },
      {
        "sound":"ri",
        "kana":"\u30ea"
      },
      {
        "sound":"ru",
        "kana":"\u30eb"
      },
      {
        "sound":"re",
        "kana":"\u30ec"
      },
      {
        "sound":"ro",
        "kana":"\u30ed"
      }
    ],
    [
      {
        "sound":"wa",
        "kana":"\u30ef"
      },
      {
        "sound":"wi",
        "kana":"\u30f0"
      },
      {
        "sound":"we",
        "kana":"\u30f1"
      },
      {
        "sound":"wo",
        "kana":"\u30f2"
      }
    ],
    [
      {
        "sound":"n",
        "kana":"\u30f3"
      }
    ],
    [
      {
        "sound":"ga",
        "kana":"\u30ac"
      },
      {
        "sound":"gi",
        "kana":"\u30ae"
      },
      {
        "sound":"gu",
        "kana":"\u30b0"
      },
      {
        "sound":"ge",
        "kana":"\u30b2"
      },
      {
        "sound":"go",
        "kana":"\u30b4"
      }
    ],
    [
      {
        "sound":"za",
        "kana":"\u30b6"
      },
      {
        "sound":"ji",
        "kana":"\u30b8"
      },
      {
        "sound":"zu",
        "kana":"\u30ba"
      },
      {
        "sound":"ze",
        "kana":"\u30bc"
      },
      {
        "sound":"zo",
        "kana":"\u30be"
      }
    ],
    [
      {
        "sound":"da",
        "kana":"\u30c0"
      },
      {
        "sound":"ji",
        "kana":"\u30c2"
      },
      {
        "sound":"zu",
        "kana":"\u30c5"
      },
      {
        "sound":"de",
        "kana":"\u30c7"
      },
      {
        "sound":"do",
        "kana":"\u30c9"
      }
    ],
    [
      {
        "sound":"ba",
        "kana":"\u30d0"
      },
      {
        "sound":"bi",
        "kana":"\u30d3"
      },
      {
        "sound":"bu",
        "kana":"\u30d6"
      },
      {
        "sound":"be",
        "kana":"\u30d9"
      },
      {
        "sound":"bo",
        "kana":"\u30dc"
      }
    ],
    [
      {
        "sound":"pa",
        "kana":"\u30d1"
      },
      {
        "sound":"pi",
        "kana":"\u30d4"
      },
      {
        "sound":"pu",
        "kana":"\u30d7"
      },
      {
        "sound":"pe",
        "kana":"\u30da"
      },
      {
        "sound":"po",
        "kana":"\u30dd"
      }
    ],
    [
      {
        "sound":"kya",
        "kana":"\u30ad\u30e3"
      },
      {
        "sound":"kyu",
        "kana":"\u30ad\u30e5"
      },
      {
        "sound":"kyo",
        "kana":"\u30ad\u30e7"
      }
    ],
    [
      {
        "sound":"sha",
        "kana":"\u30b7\u30e3"
      },
      {
        "sound":"shu",
        "kana":"\u30b7\u30e5"
      },
      {
        "sound":"sho",
        "kana":"\u30b7\u30e7"
      }
    ],
    [
      {
        "sound":"cha",
        "kana":"\u30c1\u30e3"
      },
      {
        "sound":"chu",
        "kana":"\u30c1\u30e5"
      },
      {
        "sound":"cho",
        "kana":"\u30c1\u30e7"
      }
    ],
    [
      {
        "sound":"nya",
        "kana":"\u30cb\u30e3"
      },
      {
        "sound":"nyu",
        "kana":"\u30cb\u30e5"
      },
      {
        "sound":"nyo",
        "kana":"\u30cb\u30e7"
      }
    ],
    [
      {
        "sound":"hya",
        "kana":"\u30d2\u30e3"
      },
      {
        "sound":"hyu",
        "kana":"\u30d2\u30e5"
      },
      {
        "sound":"hyo",
        "kana":"\u30d2\u30e7"
      }
    ],
    [
      {
        "sound":"mya",
        "kana":"\u30df\u30e3"
      },
      {
        "sound":"myu",
        "kana":"\u30df\u30e5"
      },
      {
        "sound":"myo",
        "kana":"\u30df\u30e7"
      }
    ],
    [
      {
        "sound":"rya",
        "kana":"\u30ea\u30e3"
      },
      {
        "sound":"ryu",
        "kana":"\u30ea\u30e5"
      },
      {
        "sound":"ryo",
        "kana":"\u30ea\u30e7"
      }
    ],
    [
      {
        "sound":"gya",
        "kana":"\u30ae\u30e3"
      },
      {
        "sound":"gyu",
        "kana":"\u30ae\u30e5"
      },
      {
        "sound":"gyo",
        "kana":"\u30ae\u30e7"
      }
    ],
    [
      {
        "sound":"ja",
        "kana":"\u30b8\u30e3"
      },
      {
        "sound":"ju",
        "kana":"\u30b8\u30e5"
      },
      {
        "sound":"jo",
        "kana":"\u30b8\u30e7"
      }
    ],
    [
      {
        "sound":"ja",
        "kana":"\u30c2\u30e3"
      },
      {
        "sound":"ju",
        "kana":"\u30c2\u30e5"
      },
      {
        "sound":"jo",
        "kana":"\u30c2\u30e7"
      }
    ],
    [
      {
        "sound":"bya",
        "kana":"\u30d3\u30e3"
      },
      {
        "sound":"byu",
        "kana":"\u30d3\u30e5"
      },
      {
        "sound":"byo",
        "kana":"\u30d3\u30e7"
      }
    ],
    [
      {
        "sound":"pya",
        "kana":"\u30d4\u30e3"
      },
      {
        "sound":"pyu",
        "kana":"\u30d4\u30e5"
      },
      {
        "sound":"pyo",
        "kana":"\u30d4\u30e7"
      }
    ]
  ]
}
